version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: always
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: attendance_system
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
